version: '2'

services:
    mysqlapi:
        image: ambientum/mysql:5.7
        container_name: mysqlapi
        volumes:
          - ./mysql:/var/lib/mysql
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=api
          - MYSQL_PASSWORD=api
          - MYSQL_DATABASE=api
          - MYSQL_USER=api

    appapi:
        image: ambientum/php:7.0-caddy
        container_name: appapi
        volumes:
          - .:/var/www/app
        ports:
          - "80:8080"
        links:
          - mysqlapi